name: Generate Metrics

on:
  schedule:
    # Runs every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Generate GitHub Metrics
      uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        user: Adarsh0427
        template: classic
        base: header, activity, community, repositories, metadata
        config_timezone: Asia/Kolkata
        
        # Languages plugin
        plugin_languages: yes
        plugin_languages_analysis_timeout: 15
        plugin_languages_categories: markup, programming
        plugin_languages_colors: github
        plugin_languages_limit: 8
        plugin_languages_recent_categories: markup, programming
        plugin_languages_recent_days: 14
        plugin_languages_recent_load: 300
        plugin_languages_sections: most-used
        plugin_languages_threshold: 0%
        
        # Activity plugin
        plugin_activity: yes
        plugin_activity_days: 14
        plugin_activity_filter: all
        plugin_activity_limit: 5
        plugin_activity_load: 300
        plugin_activity_visibility: all
